on: push
jobs:
  onepass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET_KEY: "op://Development/test-credential/username"
          SECRET_VALUE: "op://Development/test-credential/password"
          
      - name: Print masked secret
        run: |-
          echo "Secret ${{ steps.op-load-secret.outputs.SECRET_KEY }}: ${{ steps.op-load-secret.outputs.SECRET_VALUE }}"
